[package]
name = "rustreexo"
version = "0.3.0"
authors = ["Calvin Kim <calvin@kcalvinalvin.info>"]
edition = "2018"
description = "A Rust implementation of Utreexo"
license = "MIT"
repository = "https://github.com/mit-dci/rustreexo"
readme = "README.md"
homepage = "https://github.com/mit-dci/rustreexo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"], optional = true }

[dependencies.sha2]
git = "https://github.com/risc0/RustCrypto-hashes"
tag = "sha2-v0.10.8-risczero.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"

[features]
with-serde = ["serde"]
default = []

[[example]]
name = "simple-stump-update"

[[example]]
name = "proof-update"
